export const SUCCESS = 'SUCCESS'

export const FAILURE = 'FAILURE'

export const CHANGE_TEXT = 'CHANGE_TEXT'

// BEGIN, SUCCESS, FAILURE
export const BUSCA_JOGADORES_BEGIN = 'BUSCA_JOGADORES_BEGIN';
export const BUSCA_JOGADORES_SUCCESS = 'BUSCA_JOGADORES_SUCCESS';
export const BUSCA_JOGADORES_FAILURE = 'BUSCA_JOGADORES_FAILURE';