// BEGIN, SUCCESS, FAILURE
export const LISTA_JOGADORES_BEGIN = 'LISTA_JOGADORES_BEGIN';
export const LISTA_JOGADORES_SUCCESS = 'LISTA_JOGADORES_SUCCESS';
export const LISTA_JOGADORES_FAILURE = 'LISTA_JOGADORES_FAILURE';

export const BUSCA_JOGADOR_BEGIN = 'BUSCA_JOGADOR_BEGIN';
export const BUSCA_JOGADOR_SUCCESS = 'BUSCA_JOGADOR_SUCCESS';
export const BUSCA_JOGADOR_FAILURE = 'BUSCA_JOGADOR_FAILURE';

export const GRAVAR_JOGADOR_SUCCESS = 'GRAVAR_JOGADOR_SUCCESS';
export const GRAVAR_JOGADOR_FAILURE = 'GRAVAR_JOGADOR_FAILURE';